name: Build macOS binaries

on:
  push:
    branches:
      - '**'
      - '!appveyor-*'
      - '!freebsd-*'
      - '!pr-review*'
      - '!win32-*'
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-13
    steps:
    - name: Check tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "Building tag ${{ github.ref }}"
    - uses: actions/checkout@v4
    - name: Unbreak python in github actions
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
        sudo rm -rf /Library/Frameworks/Python.framework/
        brew install --force python3 && brew unlink python3 && brew unlink python3 && brew link --overwrite python3
    - name: Install
      shell: bash
      run: |
        # Keep this package list in sync with the docs:
        # https://github.com/dune3d/dune3d-docs/blob/main/build-macos.rst
        brew install \
          adwaita-icon-theme \
          cmake \
          eigen \
          glm \
          gtk4 \
          gtkmm4 \
          librsvg \
          llvm \
          meson \
          opencascade \
          pkg-config \
          pygobject3 \
          python@3

        # glibmm's bottle appears to be broken and will currently result in the following error:
        #
        # ld: Undefined symbols:
        #   Glib::DateTime::create_now_local(long long), referenced from:
        #     dune3d::Dune3DApplication::UserConfig::load(std::__1::__fs::filesystem::path const&) in src_dune3d_application.cpp.o
        #
        # Rebuilding glibmm from source appears to work around the issue for now.
        brew reinstall -s glibmm
    - name: Build
      run: bash scripts/build_macos.sh && otool -L build/dune3d
